import type { ItemProperties, ItemType } from "../types";

export const ITEM_REGISTRY: Record<ItemType, ItemProperties> = {
  // Resources
  wood: {
    type: "wood",
    category: "resource",
    label: "Wood",
    stackSize: 75,
    baseValue: 1,
    weight: 1.0,
    flammability: 1.0,
    nutrition: 0,
    spoilageRate: 0,
  },
  stone: {
    type: "stone",
    category: "resource",
    label: "Stone",
    stackSize: 75,
    baseValue: 1,
    weight: 1.5,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  iron: {
    type: "iron",
    category: "resource",
    label: "Iron",
    stackSize: 75,
    baseValue: 3,
    weight: 1.2,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  gold: {
    type: "gold",
    category: "resource",
    label: "Gold",
    stackSize: 75,
    baseValue: 10,
    weight: 1.5,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  silver: {
    type: "silver",
    category: "resource",
    label: "Silver",
    stackSize: 75,
    baseValue: 5,
    weight: 1.3,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  coal: {
    type: "coal",
    category: "resource",
    label: "Coal",
    stackSize: 75,
    baseValue: 2,
    weight: 0.8,
    flammability: 1.0,
    nutrition: 0,
    spoilageRate: 0,
  },
  cloth: {
    type: "cloth",
    category: "resource",
    label: "Cloth",
    stackSize: 75,
    baseValue: 2,
    weight: 0.3,
    flammability: 0.8,
    nutrition: 0,
    spoilageRate: 0,
  },
  leather: {
    type: "leather",
    category: "resource",
    label: "Leather",
    stackSize: 75,
    baseValue: 2,
    weight: 0.4,
    flammability: 0.5,
    nutrition: 0,
    spoilageRate: 0,
  },

  // Food
  meat: {
    type: "meat",
    category: "food",
    label: "Raw Meat",
    stackSize: 50,
    baseValue: 2,
    weight: 0.5,
    flammability: 0,
    nutrition: 0.3,
    spoilageRate: 0.01, // Spoils fastest — raw meat
  },
  berries: {
    type: "berries",
    category: "food",
    label: "Berries",
    stackSize: 50,
    baseValue: 1,
    weight: 0.1,
    flammability: 0,
    nutrition: 0.1,
    spoilageRate: 0.006, // Medium spoilage — raw plant
  },
  vegetable: {
    type: "vegetable",
    category: "food",
    label: "Vegetable",
    stackSize: 50,
    baseValue: 1,
    weight: 0.3,
    flammability: 0,
    nutrition: 0.2,
    spoilageRate: 0.006, // Medium spoilage — raw plant
  },
  meal_simple: {
    type: "meal_simple",
    category: "food",
    label: "Simple Meal",
    stackSize: 10,
    baseValue: 5,
    weight: 0.5,
    flammability: 0,
    nutrition: 0.8,
    spoilageRate: 0.003, // Cooked meals spoil slower
  },
  meal_fine: {
    type: "meal_fine",
    category: "food",
    label: "Fine Meal",
    stackSize: 10,
    baseValue: 10,
    weight: 0.5,
    flammability: 0,
    nutrition: 1.0,
    spoilageRate: 0.003, // Cooked meals spoil slower
  },

  // Medicine
  medicine_herbal: {
    type: "medicine_herbal",
    category: "medicine",
    label: "Herbal Medicine",
    stackSize: 25,
    baseValue: 5,
    weight: 0.3,
    flammability: 0.5,
    nutrition: 0,
    spoilageRate: 0.002,
  },
  medicine_industrial: {
    type: "medicine_industrial",
    category: "medicine",
    label: "Medicine",
    stackSize: 25,
    baseValue: 15,
    weight: 0.3,
    flammability: 0.2,
    nutrition: 0,
    spoilageRate: 0,
  },
  medicine_glitterworld: {
    type: "medicine_glitterworld",
    category: "medicine",
    label: "Glitterworld Medicine",
    stackSize: 10,
    baseValue: 50,
    weight: 0.2,
    flammability: 0.1,
    nutrition: 0,
    spoilageRate: 0,
  },

  // Weapons — Melee
  knife: {
    type: "knife",
    category: "weapon",
    label: "Knife",
    stackSize: 1,
    baseValue: 15,
    weight: 0.5,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  sword: {
    type: "sword",
    category: "weapon",
    label: "Sword",
    stackSize: 1,
    baseValue: 40,
    weight: 1.5,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  spear: {
    type: "spear",
    category: "weapon",
    label: "Spear",
    stackSize: 1,
    baseValue: 25,
    weight: 1.8,
    flammability: 0.3,
    nutrition: 0,
    spoilageRate: 0,
  },
  club: {
    type: "club",
    category: "weapon",
    label: "Club",
    stackSize: 1,
    baseValue: 8,
    weight: 2.0,
    flammability: 0.6,
    nutrition: 0,
    spoilageRate: 0,
  },

  // Weapons — Ranged
  bow: {
    type: "bow",
    category: "weapon",
    label: "Bow",
    stackSize: 1,
    baseValue: 30,
    weight: 1.0,
    flammability: 0.5,
    nutrition: 0,
    spoilageRate: 0,
  },
  pistol: {
    type: "pistol",
    category: "weapon",
    label: "Pistol",
    stackSize: 1,
    baseValue: 80,
    weight: 1.2,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },

  // Tools
  pickaxe: {
    type: "pickaxe",
    category: "tool",
    label: "Pickaxe",
    stackSize: 1,
    baseValue: 20,
    weight: 2.0,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  axe: {
    type: "axe",
    category: "tool",
    label: "Axe",
    stackSize: 1,
    baseValue: 20,
    weight: 2.0,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
  hammer: {
    type: "hammer",
    category: "tool",
    label: "Hammer",
    stackSize: 1,
    baseValue: 20,
    weight: 2.0,
    flammability: 0,
    nutrition: 0,
    spoilageRate: 0,
  },
};

export function getItemProperties(type: ItemType): ItemProperties {
  return ITEM_REGISTRY[type];
}
